CC = g++
CFLAGS=-O2 -Wall -g

all: distvec linkstate

distvec: distvec_20181654.cc
#	$(CC) $(CFLAGS) -o distvec distvec_20181654.cc
linkstate: linkstate_20181654.cc
#	$(CC) $(CFLAGS) -o linkstate linkstate_20181654.cc

clean :
	rm -rf distvec linkstate *.o
